version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: io-ts
    versions:
    - 2.2.13
    - 2.2.14
    - 2.2.15
  - dependency-name: io-ts-types
    versions:
    - 0.5.13
    - 0.5.14
    - 0.5.15
  - dependency-name: express-promise-router
    versions:
    - 4.0.1
